common:
  http:
    enabled: true
    port: 8883
  socket:
    enabled: false
    port: 9000
  ws:
    enabled: false
    port: 9001
  log_mode: "debug"

specific:
  eth_server: "https://data-seed-prebsc-1-s1.bnbchain.org:8545"
