version: '3'
services:

  sai-eth-interaction:
    build:
      context: ./saiETHContractInteraction
      dockerfile: Dockerfile
    ports:
      - "8818:8018"
      - "8819:8019"
      - "8804:8804"
    volumes:
      - ./saiETHContractInteraction/build/config.yml:/srv/config.yml
      - ./saiETHContractInteraction/build/contracts.json:/srv/contracts.json
